[package]
name = "iidm-derive"
version = "0.1.0"
edition = "2021"

[dependencies]
quote = "1.0.38"
syn = { version = "2.0.98", features = ["full", "extra-traits"] }

[lib]
proc-macro = true

[dev-dependencies]
serde = {version ="1.0.218", features = ["derive"] }
serde_json = "1.0.139"
